### ISSUE TITLE
Fix vulnerable dependencies in package-lock.json

### ISSUE THREAD

**Issue by joshterrill** [joshterrill/mandible#1]
There are three dependencies in the `package-lock.json` file which have vulnurabilities:

```
hapijs / cryptiles
lodash / lodash
joyent / node-sshpk sshpk
```

Need to upgrade the versions in either the `package-lock.json` or upgrade the dependencies that reference those dependencies in `package.json`.

**Comment by khrystuk** [comment]
Hey @joshterrill! I would like to work on this.

**Comment by joshterrill** [comment]
@khrystuk Have at it!

**Comment by joshterrill** [comment]
Fixed in https://github.com/joshterrill/mandible/pull/3
